project:
  type: website

website:
  margin-header: subscribe.html
  
  title: "Jomaserver Blog"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: curriculum.qmd  
        text: "Currículo"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juauzz/jomaserver.github.io
       
format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css

editor: visual
comments:
  utterances:
    repo: juauzz/jomaserver.github.io

